//
// Created by Raina Wan on 12/9/22.
//

#ifndef PORTFOLIO_STATES_ENUM_H
#define PORTFOLIO_STATES_ENUM_H

enum states_enum {
    HIDDEN, SHOWN, DISABLED, HIT, MISS,

    BALL, BOUNCING_BALL, PONG,
    TOP_HAT_GUY, CARD, POKER, BATTLESHIP,

    LAST_STATE
};

#endif //PORTFOLIO_STATES_ENUM_H
